language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
script:
  - bash setup.sh
  - bash script.sh script.sh
sudo: required
